### ISSUE TITLE
Task 8 colab and presentation links in the README are broken

### ISSUE THREAD

**Issue by esl-lewis** [ukaea/openmc_workshop#90]
As described.

**Comment by Shimwell** [comment]
Thanks for reporting this

We haven't actually got around to making this task in colab and it is not really mentioned in the presentation as it is not part of the core tasks. So those links were in there by error. Sorry for the confusion and mess

This has been fixed by with this commit https://github.com/ukaea/openmc_workshop/commit/7626262bcbb6445465b8bd91f184f55b2e9ab140
